version: "3"
services:
  db:
    image: mysql:5.7
    volumes:
      - ./data/db:/var/lib/mysql
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
  web:
    tty: true
    stdin_open: true
    build: .
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USERNAME: root
      DB_PASSWORD: password
