validations:
  number: !ruby/regexp /\A\d*\z/
  time: !ruby/regexp /\A(0[0-9]|1[0-9]|2[0-3]):[0-5][0-9]\z/

exercise_1:
  price_per_cup: 490 # yen
  price_within_discount_time: 290 # yen
  price_with_voucher: 100 # yen

excercise10:
  rank:
    silver  : 1
    gold    : 2
    platinum: 3
