validations:
  number: !ruby/regexp /\A\d*\z/
  time: !ruby/regexp /\A(0[0-9]|1[0-9]|2[0-3]):[0-5][0-9]\z/
  date: !ruby/regexp /\d{4}\-(0?[1-9]|1[012])\-(0?[1-9]|[12][0-9]|3[01])*/

exercise_1:
  price_per_cup: 490 # yen
  price_within_discount_time: 290 # yen
  price_with_voucher: 100 # yen

exercise_4:
  date_month_format: '%d-%m'
  date_fomart: '%d-%m-%Y'
  holiday: 
    - 01-01
    - 30-04
    - 01-05
    - 02-09
    - 05-09
    - 27-09
  type_color:
    - red
    - blue
    - black

exercise_5:
  min_bill_for_discount: 1500 # yen
  discount_with_voucher: 20 # %

exercise_6:
  discount_level_1: 2000 # yen
  discount_level_2: 5000 # yen
  level_1_free_parking_time: 60 # minutes
  level_2_free_parking_time: 120 # minutes
  extra_free_parking_time_for_movie: 180 # minutes
